/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 11:30:10 GMT 2020
 */

package com.recruit.recruitment.model.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.recruit.recruitment.model.pojo.Role;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class Role_ESTest extends Role_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Role role0 = new Role();
      role0.setRolename("c4(Kd`[Z`vq?XIU8");
      String string0 = role0.getRolename();
      assertEquals("c4(Kd`[Z`vq?XIU8", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Role role0 = new Role();
      Integer integer0 = new Integer(0);
      role0.setRoleid(integer0);
      Integer integer1 = role0.getRoleid();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Role role0 = new Role();
      Integer integer0 = new Integer(1);
      role0.setRoleid(integer0);
      Integer integer1 = role0.getRoleid();
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Role role0 = new Role();
      Integer integer0 = new Integer((-374));
      role0.setRoleid(integer0);
      Integer integer1 = role0.getRoleid();
      assertEquals((-374), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Role role0 = new Role();
      role0.setRolename((String) null);
      assertNull(role0.getRolename());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Role role0 = new Role();
      role0.setRolename("");
      String string0 = role0.getRolename();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Role role0 = new Role();
      String string0 = role0.getRolename();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Role role0 = new Role();
      Integer integer0 = role0.getRoleid();
      assertNull(integer0);
  }
}
