/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 09 22:26:07 GMT 2020
 */

package com.recruit.recruitment.model.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import com.recruit.recruitment.model.entity.StatusCode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class StatusCode_ESTest extends StatusCode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StatusCode statusCode0 = new StatusCode();
      assertEquals(403, StatusCode.ACCESS_ERROR);
  }
}
