/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Apr 10 11:32:09 GMT 2020
 */

package com.recruit.recruitment.serviceImpl;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class JobServiceImpl_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.recruit.recruitment.serviceImpl.JobServiceImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "MS950"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Jack\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "TW"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Jack\\Documents\\Java\\recruitment-go\\recruitment-server"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Jack"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "Jack"); 
    java.lang.System.setProperty("user.timezone", "Europe/London"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(JobServiceImpl_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.ibatis.annotations.Options",
      "com.recruit.recruitment.mapper.JobSqlProvider",
      "org.springframework.beans.factory.annotation.Autowired",
      "org.apache.ibatis.mapping.StatementType",
      "com.recruit.recruitment.model.pojo.Role",
      "org.apache.ibatis.annotations.UpdateProvider",
      "com.recruit.recruitment.serviceImpl.JobServiceImpl",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "io.jsonwebtoken.Claims",
      "com.recruit.recruitment.utils.JwtTokenUtil",
      "org.apache.ibatis.mapping.FetchType",
      "org.apache.ibatis.annotations.Results",
      "org.springframework.stereotype.Service",
      "com.fasterxml.jackson.annotation.JsonFormat$Shape",
      "org.springframework.security.core.userdetails.UserDetails",
      "org.apache.ibatis.type.TypeHandler",
      "org.springframework.stereotype.Indexed",
      "org.apache.ibatis.type.TypeReference",
      "org.apache.ibatis.annotations.Options$FlushCachePolicy",
      "org.apache.ibatis.annotations.Result",
      "org.apache.ibatis.annotations.Insert",
      "com.recruit.recruitment.mapper.UserSqlProvider",
      "org.apache.ibatis.annotations.Select",
      "org.apache.ibatis.annotations.Many",
      "com.fasterxml.jackson.annotation.JsonFormat$Feature",
      "com.recruit.recruitment.model.pojo.Job",
      "com.recruit.recruitment.mapper.JobMapper",
      "com.recruit.recruitment.model.pojo.User",
      "org.apache.ibatis.mapping.ResultSetType",
      "org.apache.ibatis.annotations.Delete",
      "com.fasterxml.jackson.annotation.OptBoolean",
      "com.fasterxml.jackson.annotation.JsonFormat",
      "org.apache.ibatis.type.UnknownTypeHandler",
      "com.recruit.recruitment.mapper.UserMapper",
      "org.apache.ibatis.type.BaseTypeHandler",
      "io.jsonwebtoken.ClaimsMutator",
      "org.springframework.stereotype.Component",
      "org.apache.ibatis.annotations.One",
      "com.recruit.recruitment.service.JobService",
      "com.recruit.recruitment.config.JwtConfig",
      "org.apache.ibatis.type.JdbcType",
      "org.apache.ibatis.annotations.InsertProvider",
      "org.apache.ibatis.annotations.Update"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.recruit.recruitment.mapper.JobMapper", false, JobServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.mapper.UserMapper", false, JobServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.model.pojo.Job", false, JobServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.model.pojo.User", false, JobServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.utils.JwtTokenUtil", false, JobServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("javax.servlet.http.HttpServletRequest", false, JobServiceImpl_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(JobServiceImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.recruit.recruitment.serviceImpl.JobServiceImpl",
      "com.fasterxml.jackson.annotation.JsonFormat$Shape",
      "com.fasterxml.jackson.annotation.OptBoolean",
      "com.recruit.recruitment.model.pojo.Job",
      "org.apache.ibatis.type.JdbcType",
      "org.apache.ibatis.mapping.FetchType",
      "com.recruit.recruitment.utils.JwtTokenUtil",
      "com.recruit.recruitment.model.pojo.User",
      "org.apache.ibatis.annotations.Options$FlushCachePolicy",
      "org.apache.ibatis.mapping.ResultSetType",
      "org.apache.ibatis.mapping.StatementType"
    );
  }
}
