/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 11:27:28 GMT 2020
 */

package com.recruit.recruitment.serviceImpl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.recruit.recruitment.mapper.ScoreMapper;
import com.recruit.recruitment.mapper.UserMapper;
import com.recruit.recruitment.model.pojo.Score;
import com.recruit.recruitment.model.pojo.User;
import com.recruit.recruitment.serviceImpl.ScoreServiceImpl;
import com.recruit.recruitment.utils.JwtTokenUtil;
import javax.servlet.http.HttpServletRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class ScoreServiceImpl_ESTest extends ScoreServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ScoreServiceImpl scoreServiceImpl0 = new ScoreServiceImpl();
      JwtTokenUtil jwtTokenUtil0 = mock(JwtTokenUtil.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(jwtTokenUtil0).getUsernameFromRequest(any(javax.servlet.http.HttpServletRequest.class));
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "jwtTokenUtil", (Object) jwtTokenUtil0);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "request", (Object) httpServletRequest0);
      ScoreMapper scoreMapper0 = mock(ScoreMapper.class, new ViolatedAssumptionAnswer());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "scoreMapper", (Object) scoreMapper0);
      UserMapper userMapper0 = mock(UserMapper.class, new ViolatedAssumptionAnswer());
      doReturn((User) null).when(userMapper0).selectByUsername(anyString());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "userMapper", (Object) userMapper0);
      Injector.validateBean(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class);
      Integer integer0 = new Integer(4126);
      // Undeclared exception!
      try { 
        scoreServiceImpl0.findApplicationScoreByMarker(integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.recruit.recruitment.serviceImpl.ScoreServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ScoreServiceImpl scoreServiceImpl0 = new ScoreServiceImpl();
      JwtTokenUtil jwtTokenUtil0 = mock(JwtTokenUtil.class, new ViolatedAssumptionAnswer());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "jwtTokenUtil", (Object) jwtTokenUtil0);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "request", (Object) httpServletRequest0);
      ScoreMapper scoreMapper0 = mock(ScoreMapper.class, new ViolatedAssumptionAnswer());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "scoreMapper", (Object) scoreMapper0);
      UserMapper userMapper0 = mock(UserMapper.class, new ViolatedAssumptionAnswer());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "userMapper", (Object) userMapper0);
      Injector.validateBean(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class);
      // Undeclared exception!
      try { 
        scoreServiceImpl0.deleteScoreRelation((Score) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.recruit.recruitment.serviceImpl.ScoreServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ScoreServiceImpl scoreServiceImpl0 = new ScoreServiceImpl();
      JwtTokenUtil jwtTokenUtil0 = mock(JwtTokenUtil.class, new ViolatedAssumptionAnswer());
      doReturn("#{userid,jdbcType=INTEGER}").when(jwtTokenUtil0).getUsernameFromRequest(any(javax.servlet.http.HttpServletRequest.class));
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "jwtTokenUtil", (Object) jwtTokenUtil0);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "request", (Object) httpServletRequest0);
      ScoreMapper scoreMapper0 = mock(ScoreMapper.class, new ViolatedAssumptionAnswer());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "scoreMapper", (Object) scoreMapper0);
      User user0 = mock(User.class, new ViolatedAssumptionAnswer());
      doReturn((Integer) null).when(user0).getUserid();
      UserMapper userMapper0 = mock(UserMapper.class, new ViolatedAssumptionAnswer());
      doReturn(user0).when(userMapper0).selectByUsername(anyString());
      Injector.inject(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class, "userMapper", (Object) userMapper0);
      Injector.validateBean(scoreServiceImpl0, (Class<?>) ScoreServiceImpl.class);
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        scoreServiceImpl0.findApplicationScoreByMarker(integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.recruit.recruitment.serviceImpl.ScoreServiceImpl", e);
      }
  }
}
