/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 09 22:23:55 GMT 2020
 */

package com.recruit.recruitment.config;

import org.junit.Test;
import static org.junit.Assert.*;
import com.recruit.recruitment.config.JwtConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JwtConfig_ESTest extends JwtConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      jwtConfig0.setTime(2935L);
      long long0 = jwtConfig0.getTime();
      assertEquals(2935L, long0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      jwtConfig0.setTime((-37L));
      long long0 = jwtConfig0.getTime();
      assertEquals((-37L), long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      jwtConfig0.setSecret("");
      String string0 = jwtConfig0.getSecret();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      jwtConfig0.setPrefix("TOKEN_");
      String string0 = jwtConfig0.getPrefix();
      assertEquals("TOKEN_", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      jwtConfig0.setHeader("QsBn!");
      String string0 = jwtConfig0.getHeader();
      assertEquals("QsBn!", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      jwtConfig0.setHeader("");
      String string0 = jwtConfig0.getHeader();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      jwtConfig0.setSecret("TOKEN_");
      String string0 = jwtConfig0.getSecret();
      assertEquals("TOKEN_", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      long long0 = jwtConfig0.getTime();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      String string0 = jwtConfig0.getHeader();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      jwtConfig0.setPrefix("");
      String string0 = jwtConfig0.getPrefix();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      String string0 = jwtConfig0.getSecret();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JwtConfig jwtConfig0 = new JwtConfig();
      String string0 = jwtConfig0.getPrefix();
      assertNull(string0);
  }
}
