/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 09 22:28:52 GMT 2020
 */

package com.recruit.recruitment.config;

import org.junit.Test;
import static org.junit.Assert.*;
import com.recruit.recruitment.config.RabbitMqConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RabbitMqConfig_ESTest extends RabbitMqConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RabbitMqConfig rabbitMqConfig0 = new RabbitMqConfig();
  }
}
