/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Apr 10 11:07:20 GMT 2020
 */

package com.recruit.recruitment.config;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ScheduledTaskConfig_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.recruit.recruitment.config.ScheduledTaskConfig"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "MS950"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Jack\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "TW"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Jack\\Documents\\Java\\recruitment-go\\recruitment-server"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Jack"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "Jack"); 
    java.lang.System.setProperty("user.timezone", "Europe/London"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ScheduledTaskConfig_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.expression.ExpressionException",
      "org.springframework.beans.factory.annotation.Autowired",
      "com.rabbitmq.client.AMQP$Queue$DeleteOk",
      "org.springframework.core.ParameterizedTypeReference$1",
      "org.springframework.core.NestedExceptionUtils",
      "org.springframework.amqp.support.converter.MessageConversionException",
      "org.apache.ibatis.type.ObjectTypeHandler",
      "com.rabbitmq.client.AMQP$Queue$BindOk",
      "com.rabbitmq.client.AMQP$BasicProperties",
      "org.springframework.amqp.rabbit.support.ListenerContainerAware",
      "org.springframework.transaction.support.ResourceHolder",
      "com.recruit.recruitment.mapper.ResumeMapper",
      "org.springframework.amqp.core.Correlation",
      "com.recruit.recruitment.mapper.EvaluatorMapper",
      "org.springframework.core.AttributeAccessor",
      "org.apache.ibatis.exceptions.IbatisException",
      "org.apache.ibatis.type.JdbcType",
      "org.springframework.amqp.AmqpRejectAndDontRequeueException",
      "org.springframework.amqp.AmqpException",
      "com.rabbitmq.client.DeliverCallback",
      "org.apache.ibatis.annotations.Options",
      "org.springframework.amqp.rabbit.connection.CorrelationData",
      "com.rabbitmq.client.AMQP$Exchange$BindOk",
      "com.recruit.recruitment.mapper.NotificationSqlProvider",
      "com.rabbitmq.client.ReturnCallback",
      "com.rabbitmq.client.ShutdownNotifier",
      "org.springframework.retry.RetryPolicy",
      "com.rabbitmq.client.AMQP$Confirm$SelectOk",
      "org.springframework.amqp.rabbit.core.RabbitOperations$OperationsCallback",
      "com.recruit.recruitment.mapper.NotificationMapper",
      "org.springframework.beans.factory.BeanFactoryAware",
      "com.rabbitmq.client.AMQP$Basic$RecoverOk",
      "org.apache.ibatis.session.Configuration",
      "org.springframework.stereotype.Indexed",
      "org.springframework.lang.Nullable",
      "org.springframework.expression.TypedValue",
      "com.rabbitmq.client.ReturnListener",
      "com.recruit.recruitment.mapper.PostMapper",
      "org.springframework.amqp.core.MessageListener",
      "org.springframework.amqp.core.AmqpMessageReturnedException",
      "org.springframework.beans.BeansException",
      "org.springframework.context.Lifecycle",
      "org.springframework.expression.ExpressionParser",
      "org.springframework.beans.factory.ObjectFactory",
      "org.springframework.expression.TypeComparator",
      "com.recruit.recruitment.model.pojo.Evaluator",
      "org.springframework.beans.factory.BeanFactory",
      "org.springframework.amqp.AmqpIOException",
      "com.rabbitmq.client.AMQP$Tx$CommitOk",
      "com.rabbitmq.client.AMQP",
      "org.springframework.amqp.core.AmqpTemplate",
      "com.rabbitmq.client.Connection",
      "org.elasticsearch.index.VersionType",
      "org.apache.ibatis.mapping.FetchType",
      "org.springframework.retry.RecoveryCallback",
      "org.springframework.data.elasticsearch.annotations.Document",
      "org.apache.ibatis.type.TypeReference",
      "org.springframework.core.SpringProperties",
      "org.apache.ibatis.annotations.Result",
      "com.rabbitmq.client.impl.AMQContentHeader",
      "com.rabbitmq.client.GetResponse",
      "org.springframework.core.NestedRuntimeException",
      "org.springframework.expression.TypeConverter",
      "org.springframework.amqp.support.converter.MessageConverter",
      "org.springframework.expression.EvaluationContext",
      "com.rabbitmq.client.BlockedListener",
      "org.springframework.retry.RetryCallback",
      "org.springframework.amqp.core.Address",
      "org.apache.ibatis.annotations.Update",
      "org.springframework.beans.factory.Aware",
      "org.springframework.amqp.core.MessageProperties",
      "com.rabbitmq.client.BasicProperties",
      "com.rabbitmq.client.ShutdownSignalException",
      "org.springframework.expression.EvaluationException",
      "com.rabbitmq.client.AMQP$Tx$SelectOk",
      "org.springframework.amqp.rabbit.core.ConsumeOkNotReceivedException",
      "org.springframework.retry.backoff.BackOffPolicy",
      "com.rabbitmq.utility.SensibleClone",
      "com.rabbitmq.client.AMQP$Tx$RollbackOk",
      "org.springframework.amqp.rabbit.core.CorrelationDataPostProcessor",
      "org.springframework.expression.TypeLocator",
      "com.rabbitmq.client.Method",
      "org.springframework.beans.factory.BeanNameAware",
      "org.springframework.amqp.rabbit.core.RabbitTemplate",
      "org.springframework.amqp.rabbit.connection.RabbitResourceHolder",
      "com.rabbitmq.client.AMQP$Exchange$UnbindOk",
      "org.springframework.amqp.rabbit.core.RabbitTemplate$TemplateConsumer",
      "org.springframework.data.annotation.Persistent",
      "org.apache.ibatis.executor.result.ResultMapException",
      "org.apache.ibatis.mapping.ResultSetType",
      "org.springframework.amqp.rabbit.core.RabbitTemplate$ReturnCallback",
      "com.rabbitmq.client.impl.Frame",
      "org.springframework.expression.spel.SpelParserConfiguration",
      "com.recruit.recruitment.mapper.UserMapper",
      "com.recruit.recruitment.model.pojo.Notification",
      "com.recruit.recruitment.model.pojo.Post",
      "org.apache.ibatis.annotations.One",
      "org.springframework.retry.RetryContext",
      "com.rabbitmq.client.AMQP$Queue$UnbindOk",
      "org.springframework.amqp.rabbit.connection.ConnectionListener",
      "org.springframework.retry.backoff.BackOffInterruptedException",
      "com.rabbitmq.client.impl.AMQBasicProperties",
      "org.elasticsearch.common.io.stream.StreamInput",
      "org.springframework.retry.ExhaustedRetryException",
      "org.apache.ibatis.annotations.InsertProvider",
      "org.springframework.retry.policy.RetryContextCache",
      "org.springframework.amqp.support.converter.SmartMessageConverter",
      "org.elasticsearch.common.io.stream.StreamOutput",
      "org.springframework.expression.PropertyAccessor",
      "org.springframework.util.concurrent.SettableListenableFuture",
      "org.springframework.util.ErrorHandler",
      "com.rabbitmq.client.ContentHeader",
      "org.apache.ibatis.annotations.Options$FlushCachePolicy",
      "org.apache.ibatis.annotations.Insert",
      "com.rabbitmq.client.impl.ContentHeaderPropertyWriter",
      "org.springframework.amqp.rabbit.connection.Connection",
      "org.springframework.amqp.rabbit.core.RabbitOperations",
      "com.recruit.recruitment.model.pojo.User",
      "org.springframework.amqp.rabbit.connection.RabbitAccessor",
      "com.recruit.recruitment.config.ScheduledTaskConfig",
      "org.springframework.amqp.rabbit.support.ConsumerCancelledException",
      "com.rabbitmq.client.ShutdownListener",
      "com.rabbitmq.client.Channel",
      "org.springframework.retry.RetryOperations",
      "org.springframework.amqp.rabbit.core.RabbitTemplate$ConfirmCallback",
      "com.rabbitmq.client.ConfirmListener",
      "org.springframework.util.concurrent.ListenableFuture",
      "org.springframework.core.ParameterizedTypeReference",
      "org.springframework.expression.ParserContext",
      "org.apache.ibatis.mapping.StatementType",
      "org.springframework.amqp.rabbit.support.MessagePropertiesConverter",
      "org.springframework.amqp.rabbit.support.Delivery",
      "org.elasticsearch.index.VersionType$3",
      "org.elasticsearch.index.VersionType$4",
      "org.elasticsearch.index.VersionType$1",
      "org.apache.ibatis.annotations.Results",
      "org.elasticsearch.index.VersionType$2",
      "com.rabbitmq.client.AMQP$Queue$DeclareOk",
      "org.springframework.transaction.support.ResourceHolderSupport",
      "org.springframework.amqp.core.ReplyToAddressCallback",
      "org.apache.ibatis.type.TypeException",
      "org.apache.ibatis.annotations.Select",
      "org.apache.ibatis.annotations.ResultType",
      "com.rabbitmq.client.AMQP$Queue$PurgeOk",
      "org.apache.ibatis.annotations.Many",
      "org.springframework.retry.TerminatedRetryException",
      "org.apache.ibatis.annotations.Delete",
      "org.springframework.retry.RetryState",
      "com.recruit.recruitment.mapper.ResumeSqlProvider",
      "org.springframework.util.MultiValueMap",
      "com.recruit.recruitment.mapper.EvaluatorSqlProvider",
      "com.rabbitmq.client.DefaultConsumer",
      "org.apache.ibatis.type.UnknownTypeHandler",
      "org.apache.ibatis.type.BaseTypeHandler",
      "com.rabbitmq.client.ConfirmCallback",
      "com.recruit.recruitment.model.pojo.Application",
      "org.springframework.expression.Expression",
      "org.springframework.transaction.TransactionException",
      "org.springframework.expression.spel.standard.SpelExpressionParser",
      "org.springframework.retry.support.RetryTemplate",
      "org.springframework.expression.spel.SpelCompilerMode",
      "org.springframework.amqp.core.AcknowledgeMode",
      "org.springframework.amqp.AmqpIllegalStateException",
      "org.springframework.amqp.core.MessagePostProcessor",
      "com.rabbitmq.client.Command",
      "com.rabbitmq.client.CancelCallback",
      "org.springframework.expression.OperatorOverloader",
      "org.springframework.core.ResolvableType",
      "com.rabbitmq.client.Consumer",
      "org.springframework.amqp.rabbit.connection.PendingConfirm",
      "org.springframework.amqp.rabbit.connection.PublisherCallbackChannel$Listener",
      "com.recruit.recruitment.service.ApplicationService",
      "org.springframework.expression.BeanResolver",
      "org.springframework.expression.AccessException",
      "org.springframework.amqp.core.ReceiveAndReplyCallback",
      "org.springframework.expression.spel.standard.SpelExpression",
      "com.recruit.recruitment.mapper.PostSqlProvider",
      "com.recruit.recruitment.model.pojo.Resume",
      "org.springframework.amqp.rabbit.connection.ConnectionFactory",
      "org.apache.ibatis.exceptions.PersistenceException",
      "com.rabbitmq.client.AMQP$Exchange$DeclareOk",
      "org.apache.ibatis.annotations.UpdateProvider",
      "org.springframework.amqp.rabbit.core.RabbitTemplate$2",
      "org.springframework.amqp.rabbit.core.RabbitTemplate$1",
      "org.springframework.beans.factory.InitializingBean",
      "org.springframework.beans.factory.ObjectProvider",
      "org.springframework.expression.common.TemplateAwareExpressionParser",
      "org.springframework.core.convert.TypeDescriptor",
      "org.springframework.amqp.core.Message",
      "org.springframework.retry.RetryListener",
      "org.apache.ibatis.type.TypeHandler",
      "com.rabbitmq.client.AMQP$BasicProperties$Builder",
      "org.springframework.retry.RetryException",
      "org.springframework.expression.ParseException",
      "com.recruit.recruitment.mapper.UserSqlProvider",
      "org.springframework.amqp.rabbit.core.ChannelCallback",
      "org.springframework.transaction.TransactionTimedOutException",
      "com.rabbitmq.client.BuiltinExchangeType",
      "org.springframework.stereotype.Component",
      "org.springframework.amqp.rabbit.core.RabbitTemplate$PendingReply",
      "com.rabbitmq.client.Envelope",
      "com.rabbitmq.client.ConsumerShutdownSignalCallback",
      "org.springframework.beans.factory.NoSuchBeanDefinitionException",
      "com.rabbitmq.client.AMQP$Exchange$DeleteOk",
      "org.elasticsearch.common.io.stream.Writeable"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.recruit.recruitment.mapper.EvaluatorMapper", false, ScheduledTaskConfig_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.mapper.NotificationMapper", false, ScheduledTaskConfig_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.mapper.PostMapper", false, ScheduledTaskConfig_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.mapper.ResumeMapper", false, ScheduledTaskConfig_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.mapper.UserMapper", false, ScheduledTaskConfig_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.service.ApplicationService", false, ScheduledTaskConfig_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.springframework.amqp.rabbit.core.RabbitTemplate", false, ScheduledTaskConfig_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ScheduledTaskConfig_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.recruit.recruitment.config.ScheduledTaskConfig",
      "org.elasticsearch.index.VersionType",
      "org.apache.ibatis.mapping.FetchType",
      "org.apache.ibatis.type.JdbcType",
      "org.springframework.amqp.rabbit.connection.RabbitAccessor",
      "org.springframework.expression.common.TemplateAwareExpressionParser",
      "org.springframework.expression.spel.standard.SpelExpressionParser",
      "org.springframework.core.SpringProperties",
      "org.springframework.expression.spel.SpelCompilerMode",
      "org.springframework.expression.spel.SpelParserConfiguration",
      "org.springframework.amqp.rabbit.core.RabbitTemplate",
      "org.apache.ibatis.mapping.ResultSetType",
      "org.apache.ibatis.mapping.StatementType",
      "org.apache.ibatis.annotations.Options$FlushCachePolicy"
    );
  }
}
