/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 13:02:21 GMT 2020
 */

package com.recruit.recruitment.config;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.recruit.recruitment.config.WebMvcConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WebMvcConfig_ESTest extends WebMvcConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WebMvcConfig webMvcConfig0 = new WebMvcConfig();
      ResourceHandlerRegistry resourceHandlerRegistry0 = mock(ResourceHandlerRegistry.class, new ViolatedAssumptionAnswer());
      doReturn((ResourceHandlerRegistration) null).when(resourceHandlerRegistry0).addResourceHandler(any(java.lang.String[].class));
      // Undeclared exception!
      try { 
        webMvcConfig0.addResourceHandlers(resourceHandlerRegistry0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.recruit.recruitment.config.WebMvcConfig", e);
      }
  }
}
