/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 11:15:21 GMT 2020
 */

package com.recruit.recruitment.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.recruit.recruitment.utils.FormatUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FormatUtil_ESTest extends FormatUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FormatUtil formatUtil0 = new FormatUtil();
      Integer[] integerArray0 = new Integer[1];
      Integer integer0 = new Integer(0);
      integerArray0[0] = integer0;
      boolean boolean0 = formatUtil0.checkPositive(integerArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FormatUtil formatUtil0 = new FormatUtil();
      boolean boolean0 = formatUtil0.checkMail("0@0.00");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FormatUtil formatUtil0 = new FormatUtil();
      // Undeclared exception!
      try { 
        formatUtil0.checkStringNull((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.recruit.recruitment.utils.FormatUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FormatUtil formatUtil0 = new FormatUtil();
      // Undeclared exception!
      try { 
        formatUtil0.checkObjectNull((Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.recruit.recruitment.utils.FormatUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FormatUtil formatUtil0 = new FormatUtil();
      // Undeclared exception!
      try { 
        formatUtil0.checkMail((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FormatUtil formatUtil0 = new FormatUtil();
      Integer[] integerArray0 = new Integer[7];
      Integer integer0 = new Integer(533);
      integerArray0[0] = integer0;
      Integer integer1 = new Integer((-2721));
      integerArray0[1] = integer1;
      boolean boolean0 = formatUtil0.checkPositive(integerArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FormatUtil formatUtil0 = new FormatUtil();
      Integer[] integerArray0 = new Integer[7];
      Integer integer0 = new Integer(533);
      integerArray0[0] = integer0;
      // Undeclared exception!
      try { 
        formatUtil0.checkPositive(integerArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.recruit.recruitment.utils.FormatUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Integer[] integerArray0 = new Integer[0];
      FormatUtil formatUtil0 = new FormatUtil();
      boolean boolean0 = formatUtil0.checkPositive(integerArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[4];
      FormatUtil formatUtil0 = new FormatUtil();
      boolean boolean0 = formatUtil0.checkObjectNull(stringArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "V";
      FormatUtil formatUtil0 = new FormatUtil();
      boolean boolean0 = formatUtil0.checkObjectNull(stringArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[4];
      stringArray0[0] = "v{buK!z)c8";
      stringArray0[1] = "";
      FormatUtil formatUtil0 = new FormatUtil();
      boolean boolean0 = formatUtil0.checkStringNull(stringArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FormatUtil formatUtil0 = new FormatUtil();
      String[] stringArray0 = new String[1];
      boolean boolean0 = formatUtil0.checkStringNull(stringArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "V";
      FormatUtil formatUtil0 = new FormatUtil();
      boolean boolean0 = formatUtil0.checkStringNull(stringArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FormatUtil formatUtil0 = new FormatUtil();
      boolean boolean0 = formatUtil0.checkMail("ULIp");
      assertFalse(boolean0);
  }
}
