/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Apr 09 22:27:59 GMT 2020
 */

package com.recruit.recruitment.serviceImpl;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class RoleServiceImpl_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.recruit.recruitment.serviceImpl.RoleServiceImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "MS950"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Jack\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "TW"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Jack\\Documents\\Java\\recruitment-go\\recruitment-server"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Jack"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "Jack"); 
    java.lang.System.setProperty("user.timezone", "Europe/London"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(RoleServiceImpl_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.ibatis.annotations.Select",
      "org.apache.ibatis.annotations.Many",
      "com.recruit.recruitment.mapper.RoleSqlProvider",
      "com.recruit.recruitment.serviceImpl.RoleServiceImpl",
      "org.apache.ibatis.annotations.Delete",
      "org.springframework.beans.factory.annotation.Autowired",
      "com.recruit.recruitment.model.pojo.Role",
      "org.apache.ibatis.annotations.UpdateProvider",
      "org.apache.ibatis.type.UnknownTypeHandler",
      "org.apache.ibatis.type.BaseTypeHandler",
      "org.apache.ibatis.mapping.FetchType",
      "org.springframework.stereotype.Component",
      "org.apache.ibatis.annotations.Results",
      "org.apache.ibatis.annotations.One",
      "org.springframework.stereotype.Service",
      "com.recruit.recruitment.mapper.RoleMapper",
      "org.apache.ibatis.type.JdbcType",
      "org.apache.ibatis.type.TypeHandler",
      "org.apache.ibatis.type.TypeReference",
      "org.apache.ibatis.annotations.InsertProvider",
      "com.recruit.recruitment.service.RoleService",
      "org.apache.ibatis.annotations.Update",
      "org.apache.ibatis.annotations.Result",
      "org.apache.ibatis.annotations.Insert"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.recruit.recruitment.mapper.RoleMapper", false, RoleServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.recruit.recruitment.model.pojo.Role", false, RoleServiceImpl_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(RoleServiceImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.recruit.recruitment.serviceImpl.RoleServiceImpl",
      "org.apache.ibatis.mapping.FetchType",
      "org.apache.ibatis.type.JdbcType",
      "com.recruit.recruitment.model.pojo.Role"
    );
  }
}
