/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 11:31:19 GMT 2020
 */

package com.recruit.recruitment.model.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.recruit.recruitment.model.pojo.Evaluator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Evaluator_ESTest extends Evaluator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      Integer integer0 = new Integer(0);
      evaluator0.setPostid(integer0);
      Integer integer1 = evaluator0.getPostid();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      Integer integer0 = new Integer((-1));
      evaluator0.setPostid(integer0);
      Integer integer1 = evaluator0.getPostid();
      assertEquals((-1), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      evaluator0.setEvaluatorname("");
      String string0 = evaluator0.getEvaluatorname();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      Integer integer0 = new Integer(0);
      evaluator0.setEvaluatorid(integer0);
      Integer integer1 = evaluator0.getEvaluatorid();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      Integer integer0 = new Integer((-2262));
      evaluator0.setEvaluatorid(integer0);
      Integer integer1 = evaluator0.getEvaluatorid();
      assertEquals((-2262), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      Integer integer0 = new Integer((-1));
      evaluator0.setEvaluatorid(integer0);
      Integer integer1 = evaluator0.getEvaluatorid();
      assertEquals((-1), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      evaluator0.setEvaluatorname((String) null);
      assertNull(evaluator0.getEvaluatorid());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      evaluator0.setEvaluatorname("|y;~0&b(dr1<[EQ/NpI");
      String string0 = evaluator0.getEvaluatorname();
      assertEquals("|y;~0&b(dr1<[EQ/NpI", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      Integer integer0 = evaluator0.getPostid();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      String string0 = evaluator0.getEvaluatorname();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      Integer integer0 = new Integer(1);
      evaluator0.setEvaluatorid(integer0);
      Integer integer1 = evaluator0.getEvaluatorid();
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      Integer integer0 = new Integer(1);
      evaluator0.setPostid(integer0);
      Integer integer1 = evaluator0.getPostid();
      assertEquals(1, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Evaluator evaluator0 = new Evaluator();
      Integer integer0 = evaluator0.getEvaluatorid();
      assertNull(integer0);
  }
}
