/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 10 11:24:13 GMT 2020
 */

package com.recruit.recruitment.model.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.recruit.recruitment.model.pojo.Job;
import java.util.Date;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Job_ESTest extends Job_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Job job0 = new Job();
      Integer integer0 = new Integer(0);
      job0.setUserid(integer0);
      Integer integer1 = job0.getUserid();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Job job0 = new Job();
      Integer integer0 = new Integer(2638);
      job0.setUserid(integer0);
      Integer integer1 = job0.getUserid();
      assertEquals(2638, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Job job0 = new Job();
      Integer integer0 = new Integer((-309));
      job0.setUserid(integer0);
      Integer integer1 = job0.getUserid();
      assertEquals((-309), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Job job0 = new Job();
      job0.setJobtitle("|P|c#Q&/~\"U65/8#");
      String string0 = job0.getJobtitle();
      assertEquals("|P|c#Q&/~\"U65/8#", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Job job0 = new Job();
      job0.setJobtitle("");
      String string0 = job0.getJobtitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Job job0 = new Job();
      Integer integer0 = new Integer(0);
      job0.setJobid(integer0);
      Integer integer1 = job0.getJobid();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Job job0 = new Job();
      Integer integer0 = new Integer((-2031));
      job0.setJobid(integer0);
      Integer integer1 = job0.getJobid();
      assertEquals((-2031), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Job job0 = new Job();
      Integer integer0 = new Integer(1473);
      job0.setJobid(integer0);
      Integer integer1 = job0.getJobid();
      assertEquals(1473, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Job job0 = new Job();
      job0.setJobdescript("eauXjAE&(O-;V$1");
      String string0 = job0.getJobdescript();
      assertEquals("eauXjAE&(O-;V$1", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Job job0 = new Job();
      job0.setJobdescript("");
      String string0 = job0.getJobdescript();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Job job0 = new Job();
      job0.setCompanyname("");
      String string0 = job0.getCompanyname();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Job job0 = new Job();
      job0.setJobdescript((String) null);
      assertNull(job0.getJobid());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Job job0 = new Job();
      job0.setJobtitle((String) null);
      assertNull(job0.getCompanyname());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Job job0 = new Job();
      job0.setCompanyname((String) null);
      assertNull(job0.getJobdescript());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Job job0 = new Job();
      job0.setCompanyname("5h oKqn|kb#c%y(fQ");
      String string0 = job0.getCompanyname();
      assertEquals("5h oKqn|kb#c%y(fQ", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Job job0 = new Job();
      job0.setJobend((Date) null);
      assertNull(job0.getUserid());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Job job0 = new Job();
      Integer integer0 = job0.getUserid();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Job job0 = new Job();
      Integer integer0 = job0.getJobid();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Job job0 = new Job();
      job0.setJobstart((Date) null);
      assertNull(job0.getJobid());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Job job0 = new Job();
      String string0 = job0.getJobdescript();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Job job0 = new Job();
      Date date0 = job0.getJobend();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Job job0 = new Job();
      Date date0 = job0.getJobstart();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Job job0 = new Job();
      String string0 = job0.getJobtitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Job job0 = new Job();
      String string0 = job0.getCompanyname();
      assertNull(string0);
  }
}
